name: Multi Docker Image Build

on:
  push:
    branches: [ "*", "!main" ]
  pull_request:
    branches: [ "*", "!main" ]

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Images
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}' | tr '[:upper:]' '[:lower:]')

          for DOCKERFILE in dockerfiles/*; do
            if [ -f "$DOCKERFILE" ]; then
              IMAGE_NAME_SUFFIX=$(basename "$DOCKERFILE" | sed 's/Dockerfile.//g' | tr '[:upper:]' '[:lower:]')
              IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${REPO_NAME}_${IMAGE_NAME_SUFFIX}
              docker build -f $DOCKERFILE . --tag $IMAGE_NAME:temp
            fi
          done
